Import('app_build','image_build','env')
SConscript(dirs = 'ble',exports=['app_build','image_build','env'])
SConscript(dirs = 'mesh',exports=['app_build','image_build','env'])
SConscript(dirs = 'peripheral',exports=['app_build','image_build','env'])
SConscript(dirs = 'utility',exports=['app_build','image_build','env'])

